### ISSUE TITLE
UI: Improve Error Message for Invalid Team Name Input

### ISSUE THREAD

**Issue by jonasbg** [juice-shop/multi-juicer#178]
Currently, when a user attempts to input an illegal team name, the system only displays a generic error message: Failed to create / join the team. This error message could be more descriptive and provide specific feedback on what went wrong with the suggested team name.

Here are some rules for valid team names that should be communicated in the error message (these are already available in the tooltip menu):

- The team name should not contain uppercase letters.
- The '-' character is not allowed.
- Special characters are not allowed.

By providing a more detailed error message, we can guide the user to correct their input, thus enhancing the user experience.

**Comment by J12934** [comment]
Mhh that used to work, we have a specifc error message for that which used to be shown if the team name didn't match the regex in the frontend. https://github.com/juice-shop/multi-juicer/blob/main/juice-balancer/ui/src/pages/JoinPage.js#L14

**Comment by J12934** [comment]
This is how it looks for me (after pressing create=

<img width="759" alt="Screenshot 2023-09-23 at 12 04 17" src="https://github.com/juice-shop/multi-juicer/assets/13718901/0b1cb24c-91d7-425d-80d5-2f33d41961d8">

**Comment by stuebingerb** [comment]
This was fixed with https://github.com/juice-shop/multi-juicer/pull/174 😉

**Comment by J12934** [comment]
> This was fixed with https://github.com/juice-shop/multi-juicer/pull/174 😉 
> 
> 
> 
> I wonder if it would make sense to align the error message for this and https://github.com/juice-shop/multi-juicer/issues/179, though, to have a consistent UI. But I'll leave this up to @J12934.

Sorry overlooked this. 

To me this is fine right now. I think having a different style for validation and for an actual error which was thrown for a valid input is totally fine.

I'm closing this ticket now. Thank you all for the input and feedback here 🙌
