### ISSUE TITLE
UI: Improve Feedback for Maximum Instances Limit Reached in Juice-Shop

### ISSUE THREAD

**Issue by jonasbg** [juice-shop/multi-juicer#179]
At present, when the maximum instances limit of Juice-Shop is reached, the user only receives a vague error message: Failed to create / join the team. This message does not effectively inform the user about the actual issue, which is hitting the limit for instances.

The error message could be more informative and user-friendly, for instance: 
`Max instances (35) reached, contact admin or join another team to participate.`

In addition, the error code associated with this situation is currently 500, which is not appropriate for this kind of error. It should be revised to a more suitable status code, such as 418.

**Comment by J12934** [comment]
What does it show now?

It used to show these errors in the frontend:

"Reached Maximum Instance Count. Find a Admin to handle this."
https://github.com/juice-shop/multi-juicer/blob/main/juice-balancer/src/teams/teams.js#L144

I would not want to show the user what the max instance count is configured to, so i think the error message right now is ok but yours definitly is a bit nicer :D So I'm open to chanign it to it (other than the instance count, would leave that out)

**Comment by J12934** [comment]
<img width="839" alt="Screenshot 2023-09-23 at 12 39 37" src="https://github.com/juice-shop/multi-juicer/assets/13718901/cd09e656-ce70-4afd-983e-7498727c91d8">

Changed it to show a the error message to the user :)
