### ISSUE TITLE
Insufficient cpu on DO

### ISSUE THREAD

**Issue by digininja** [juice-shop/multi-juicer#184]
I'm following the setup instructions for DigitalOcean. I've got to step 2 and ran the `get pods`. The juice-balancer pod is stuck in the pending state.

When I describe the pod I get this:

```
Warning  FailedScheduling   9m18s (x31 over 158m)   default-scheduler   0/3 nodes are available: 3 Insufficient cpu. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
```

I know nothing about kubernetes or DO setup so I'm stalled here.

How do I allocate the extra resources so the provisioning can go ahead? I'll probably be hosting about 12 users with light load in case that makes a difference.

**Comment by J12934** [comment]
Hi thanks for reporting this.

I haven't tried the DO Guide in a while will recheck when I get a chance. It's possible that the default VM sizes it's now using are not big enough anymore.

You can try if adding more nodes or adding a second node pool with bigger VM (more cpu / memory) works. You should be able to do so via the DO Web Ui.

**Comment by digininja** [comment]
I had a chat with the DO support team and they told me to do basically the same as you suggest and it worked so your prediction is probably right.

I wish I understood the setup enough to be more useful with reporting or a fix, but it was a rush job to get it all setup for a training day and now I'm tearing it all back down to stop them charging me.

I'm happy to run through the scripts again later though if you want and provide feedback as a novice user. There are definitely bits that could be expanded on, such as getting a certificate, that would help, but aren't really in your scope so I understand why you wouldn't want to cover them.

**Comment by jub0bs** [comment]
In my experience, `--size=s-2vcpu-4gb` is sufficient.

**Comment by zyrthofar** [comment]
I've run mine on a single node (`--count 1`) of `s-2vcpu-4gb`, but even then, the second team's pod didn't have enough memory. Since this is for an event lasting an afternoon, I've decided to use one of the bigger sizes, to be sure not to run into such problems during the event. Even if I leave it running until the next day, it will cost less than 10$.

```
doctl kubernetes cluster create --size s-8vcpu-32gb --count 1 juicy-k8s
```

**Comment by J12934** [comment]
Would be cool to have the DO guide updated with a machine type which should work better than the default one.

I think then we should be able to close this issue.

**Comment by digininja** [comment]
That sounds good to me. I wish I could help, but I just guessed till it
worked.

**Comment by J12934** [comment]
I mean if it works, it should probably also work for others 😅

So i guess it's can't be worse than the default one, if the default just doesn't cut it resource wise.

**Comment by digininja** [comment]
Unfortunately I deleted it straight after the class.

I've just checked the invoice and it only shows the name, not the spec.
Might be able to reverse it, 80 hours cost $6.12.
