### ISSUE TITLE
Deprecated links in score board

### ISSUE THREAD

**Issue by zyrthofar** [juice-shop/multi-juicer#194]
In the score board, the hints buttons point to URLs that might be deprecated.

For example, the first challenge in the list, Bonus Payload, point to

```
https://pwning.owasp-juice.shop/part2/xss.html#use-the-bonus-payload-in-the-dom-xss-challenge
```

instead of

```
https://pwning.owasp-juice.shop/companion-guide/latest/part2/xss.html#_use_the_bonus_payload_in_the_dom_xss_challenge
```

The [Juice Shop demo](https://demo.owasp-juice.shop/#/score-board) point to the correct URLs, so it might just be that this project uses older juice-shop images?

Let me know if I can help.

**Comment by J12934** [comment]
Hi @zyrthofar 

What MultiJuicer version are you using?

The current MultiJuicer version is using the current JuiceShop version by default, so I don't think this is a general problem.

**Comment by J12934** [comment]
Closing this as this is very likely for a older MultiJuicer version unless more information ist provided. 

Let me know if this actually is an issue on the current version
