### ISSUE TITLE
Helm charts not being published since 5.3.0

### ISSUE THREAD

**Issue by jvmdc** [juice-shop/multi-juicer#198]
The Helm chart repository (https://juice-shop.github.io/multi-juicer) only contains Helm charts for v. 5.3.0 and before.

Steps to reproduce:
1. Open https://juice-shop.github.io/multi-juicer/index.yaml (the index for the Helm chart repository)
2. Search for "version: 6" or "version: 7" without quotes
3. No results will appear

**Comment by J12934** [comment]
Please take a look at the braking changes in the 6.0.0 release. (Which are also linked from the main MultiJuicer readme)

https://github.com/juice-shop/multi-juicer/releases/tag/v6.0.0

TLDR MultiJuicer has moved to GitHub packages as the helm registry

**Comment by jvmdc** [comment]
Seems I read over the release notes a bit too fast - Only noticed the `helm repo add multi-juicer https://iteratec.github.io/multi-juicer/ => helm repo add multi-juicer https://juice-shop.github.io/multi-juicer/` line. Thanks!
