### ISSUE TITLE
Problem with Azure Guide

### ISSUE THREAD

**Issue by 007divyachawla** [juice-shop/multi-juicer#234]
On running the following command,

az aks update -n juicy-k8s -g multi-juicer --attach-acr <acr-name> getting this error.

**Could not create a role assignment for ACR. Are you an Owner on this subscription?**

Even i am admin of the subscription

**Comment by J12934** [comment]
Sorry no Idea 🤷‍♂️
Not sure if I could even help without knowing more about your azure setup. If you find out if there is something wrong with the guide could you open up a pr with a fix for it? 🙌

**Comment by 007divyachawla** [comment]
Thanks @J12934  issue is been resolved, there was an access issue from my organization.
