### ISSUE TITLE
API /balancer/score-board/

### ISSUE THREAD

**Issue by 007divyachawla** [juice-shop/multi-juicer#237]
Have created 30 teams, but when i opened the score-board URL only 24 teams is been showing , is there any way i can see all the teams.

**Comment by J12934** [comment]
No, it's limited to that for now to avoid performance issues. We might add pagination in the future but right now it only shows the top teams.

If you want to see all (active) teams check the MultiJuicer annotations on their Kubernetes deployments. E.g via: kubectl get deployments -oyaml
