### ISSUE TITLE
Teams and Instance Limit

### ISSUE THREAD

**Issue by 007divyachawla** [juice-shop/multi-juicer#238]
What is the maximum number of teams can be created in Multi-Juicer hosted on AK?
What is the maximum number of instance can be created in one team?

**Comment by J12934** [comment]
The instance limit can be configured. MultiJuicer itself has no hard upper instance limit, if your cluster can run hundreds / thousands of juice shops in parralel then MJ should support it too. You might need to scale up the number of balancer instances to handle the load
