### ISSUE TITLE
how to get scores of all teams

### ISSUE THREAD

**Issue by 007divyachawla** [juice-shop/multi-juicer#247]
Hello Sir,

I have created 50 teams, but in the score-board i can show top 24, is there any ways i can get the details of the rest 26 teams with the score and number of challenges solved.

Thanks and Regards,
Vicky Chawla

**Comment by J12934** [comment]
You can get the scores of all teams by looking at the multijuicer annotations on the Kubernetes deployments used for the teams.

kubectl get deployments -oyaml 

Then look for the multijuicer annotations. There should be a annotation with all solved challenges (and one with the score afair)
