### ISSUE TITLE
 values in values.yaml are not applied during deployment

### ISSUE THREAD

**Issue by xavierKress** [juice-shop/multi-juicer#265]
Hello,

I encountered an issue while deploying MultiJuicer v7.3.2 using Helm on an EKS cluster (AWS). The values for ctfKey and nodeEnv specified in my values.yaml file are not being applied during the deployment.

Here is the command I used to install MultiJuicer :

`helm install multi-juicer oci://ghcr.io/juice-shop/multi-juicer/helm/multi-juicer -f values.yaml -n my-namespace`

Here is the relevant part of my values.yaml configuration :

```
config:  
  maxInstances: -1  
  juiceShop:  
    ctfKey: "myCtfKey"  
    nodeEnv: "ctf"  
```

After deploying, the ctfKey and nodeEnv values are not reflected in the running instances of Juice Shop. I verified the generated manifests using helm template and the values do not seem to be included.

Could this be a bug in the Helm chart, or am I missing something in the configuration?

Thanks in advance for your help!

Best regards

**Comment by J12934** [comment]
Hi @xavierKress you've already accidentally made your config ready for MJ v8 :)
The main branch is already the v8 config. It has some breaking changes to v7, so when adjusting the values have a look at the default values for the latest v7 release :) https://github.com/juice-shop/multi-juicer/blob/v7.3.2/helm/multi-juicer/values.yaml

**Comment by xavierKress** [comment]
Hi @J12934, Thank you for your quick reply and clarification ! That explains why my configuration wasn’t working as expected. I’ll review the values for the latest v7 release and adjust my yaml file accordingly. I really appreciate your help and the link to the correct configuration. Also, thank you for your amazing work on MultiJuicer, it’s a fantastic tool that makes organizing CTFs so much easier

**Comment by J12934** [comment]
Awesome, glad to hear it :)
If you can wait for a day or so, you can also probably wait for MJ v8.
Working on finishing up the release notes right now, will publish the official v8 release once that is down :)

(Or use the release candidate rc.1, which should already work nicely :))
