### ISSUE TITLE
Team passcode reset

### ISSUE THREAD

**Issue by DerGut** [juice-shop/multi-juicer#63]
We deployed multi-juicer as part of an internal security hackathon and it was great 👍 

I noticed that a lot of the teams forgot to write down their passcode when creating their instance. Later on, teams wanted to switch browsers, laptops etc. and couldn't because the passcode was gone.

I think it would be very helpful to add the functionality to reset the passcode either in the admin interface or next to the team display card
https://github.com/iteratec/multi-juicer/blob/9dd8ceb7c28f35d66d150d9a2352f9f130241a6c/juice-balancer/ui/src/pages/JoinPage.js#L66-L68

**Comment by J12934** [comment]
Yes that would be a very useful feature.

This should not be to complicated, unless resetting the password would need to invalidate / log out existing sessions with the previous passcode. I guess in the context of MultiJuicer this would be ok to skip.

**Comment by J12934** [comment]
Has been implemented for a while now 😊
Closing this issue
